service: formly-backend
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30

functions:
  auth:
    handler: ./handlers/auth.handler
    events:
      - http:
          path: /ping
          method: GET
          cors: true
      - http:
          path: /auth/google
          method: GET
          cors: true
      - http:
          path: /auth/google/callback
          method: GET
          cors: true
      - http:
          path: /auth/github
          method: GET
          cors: true
      - http:
          path: /auth/github/callback
          method: GET
          cors: true
      - http:
          path: /auth/linkedin
          method: GET
          cors: true
      - http:
          path: /auth/linkedin/callback
          method: GET
          cors: true
      - http:
          path: /authenticate
          method: POST
          cors: true
      - http:
          path: /checkUserExists
          method: GET
          cors: true
  token:
    handler: ./handlers/token.handler
    events:
      - http:
          path: /accessToken
          method: POST
          cors: true
